export const brands = [
    {brand: "Adidas", model: "Samba OG", reference_number: "B75806"},
    {brand: "Adidas", model: "Questar Flow", reference_number: "EE8221"},
    {brand: "Adidas", model: "Stan Smith", reference_number: "M20324"},
    {brand: "Adidas", model: "RapidaRun", reference_number: "AC8295"},
    {brand: "Adidas", model: "Terrex Agravic TR", reference_number: "BC0516"},
    {brand: "Adidas", model: "Superstar", reference_number: "EG4958"},
    {brand: "Adidas", model: "Nizza Pride", reference_number: "EF2318"},
    {brand: "Adidas", model: "SL 72", reference_number: "FW1416"},
    {brand: "Adidas", model: "Matchbreak Super", reference_number: "FX2708"},
    {brand: "Adidas", model: "Zurro SPZL", reference_number: "FZ1603"},
    {brand: "Adidas", model: "Predator 20.3 FG", reference_number: "EF1645"},
    {brand: "Adidas", model: "D Rose 10 Pride", reference_number: "EH2455"},
    {brand: "Adidas", model: "Copa 20.3 Turf", reference_number: "EF1943"},
    {brand: "Adidas", model: "Adizero Adios Boost 2", reference_number: "S78010"},
    {brand: "Adidas", model: "Adizero Boston Boost 5", reference_number: "B22870"},
    {brand: "Adidas", model: "Adizero Feather Prime", reference_number: "S74427"},
    {brand: "Adidas", model: "Adizero Takumi Ren Boost 3", reference_number: "BB6415"},
    {brand: "Adidas", model: "Duramo 6", reference_number: "G64768"},
    {brand: "Adidas", model: "Energy Boost ESM", reference_number: "B27132"},
    {brand: "Adidas", model: "Kanadia 7", reference_number: "B40544"},
    {brand: "Adidas", model: "Questar Boost Techfit", reference_number: "D66488"},
    {brand: "Adidas", model: "Response Boost", reference_number: "M29706"},
    {brand: "Adidas", model: "Yeezy Boost", reference_number: "BB5350"},
    {brand: "Adidas", model: "AlphaBounce", reference_number: "BA8143"},
    {brand: "Adidas", model: "Harden Vol. 4", reference_number: "EH2224"},
    {brand: "Adidas", model: "EQT Support", reference_number: "BB1234"},
    {brand: "Adidas", model: "Dame 6", reference_number: "EH2073"},
    {brand: "Adidas", model: "D.O.N. Issue #2", reference_number: "FW8515"},
    {brand: "Adidas", model: "Harden Vol. 5", reference_number: "FZ1071"},
    {brand: "Adidas", model: "T-Mac Millennium", reference_number: "EF9844"},
    {brand: "Adidas", model: "Pro Boost Low", reference_number: "EH2456"},
    {brand: "Adidas", model: "Hoops 3.0", reference_number: "GY5432"},
    {brand: "Adidas", model: "Hoops 2.0", reference_number: "FY8626"},
    {brand: "Nike", model: "Air Max 1", reference_number: "FD9082"},
    {brand: "Nike", model: "Air Max 90", reference_number: "CW7483"},
    {brand: "Nike", model: "Air Force 1 '07", reference_number: "315122"},
    {brand: "Nike", model: "Air Jordan 1 Retro High OG", reference_number: "555088"},
    {brand: "Nike", model: "React Infinity Run Flyknit", reference_number: "CD4371"},
    {brand: "Nike", model: "Blazer Mid '77 Vintage", reference_number: "BQ6806"},
    {brand: "Nike", model: "ZoomX Vaporfly NEXT%", reference_number: "AO4568"},
    {brand: "Nike", model: "Dunk Low", reference_number: "DD1391"},
    {brand: "Nike", model: "Metcon 6", reference_number: "CT1241"},
    {brand: "Nike", model: "Pegasus Trail 3", reference_number: "DA8697"},
    {brand: "Nike", model: "SB Dunk Low Pro", reference_number: "BQ6817"},
]

