export const brands = [
    {brand: "Adidas", model: "Samba OG", reference_number: "B75806"},
    {brand: "Adidas", model: "Questar Flow", reference_number: "EE8221"},
    {brand: "Adidas", model: "Stan Smith", reference_number: "M20324"},
    {brand: "Adidas", model: "RapidaRun", reference_number: "AC8295"},
    {brand: "Adidas", model: "Terrex Agravic TR", reference_number: "BC0516"},
    {brand: "Adidas", model: "Superstar", reference_number: "EG4958"},
    {brand: "Adidas", model: "Nizza Pride", reference_number: "EF2318"},
    {brand: "Adidas", model: "SL 72", reference_number: "FW1416"},
    {brand: "Adidas", model: "Matchbreak Super", reference_number: "FX2708"},
    {brand: "Adidas", model: "Zurro SPZL", reference_number: "FZ1603"},
    {brand: "Adidas", model: "Predator 20.3 FG", reference_number: "EF1645"},
    {brand: "Adidas", model: "D Rose 10 Pride", reference_number: "EH2455"},
    {brand: "Adidas", model: "Copa 20.3 Turf", reference_number: "EF1943"},
    {brand: "Adidas", model: "Adizero Adios Boost 2", reference_number: "S78010"},
    {brand: "Adidas", model: "Adizero Boston Boost 5", reference_number: "B22870"},
    {brand: "Adidas", model: "Adizero Feather Prime", reference_number: "S74427"},
    {brand: "Adidas", model: "Adizero Takumi Ren Boost 3", reference_number: "BB6415"},
    {brand: "Adidas", model: "Duramo 6", reference_number: "G64768"},
    {brand: "Adidas", model: "Energy Boost ESM", reference_number: "B27132"},
    {brand: "Adidas", model: "Kanadia 7", reference_number: "B40544"},
    {brand: "Adidas", model: "Questar Boost Techfit", reference_number: "D66488"},
    {brand: "Adidas", model: "Response Boost", reference_number: "M29706"},
    {brand: "Adidas", model: "Yeezy Boost", reference_number: "BB5350"},
    {brand: "Adidas", model: "AlphaBounce", reference_number: "BA8143"},
    {brand: "Adidas", model: "Harden Vol. 4", reference_number: "EH2224"},
    {brand: "Adidas", model: "EQT Support", reference_number: "BB1234"},
    {brand: "Adidas", model: "Dame 6", reference_number: "EH2073"},
    {brand: "Adidas", model: "D.O.N. Issue #2", reference_number: "FW8515"},
    {brand: "Adidas", model: "Harden Vol. 5", reference_number: "FZ1071"},
    {brand: "Adidas", model: "T-Mac Millennium", reference_number: "EF9844"},
    {brand: "Adidas", model: "Pro Boost Low", reference_number: "EH2456"},
    {brand: "Adidas", model: "Hoops 3.0", reference_number: "GY5432"},
    {brand: "Adidas", model: "Hoops 2.0", reference_number: "FY8626"},
    {brand: "Adidas", model: "NMD_R1", reference_number: "FX4350"},
    {brand: "Adidas", model: "Ultraboost 21", reference_number: "FY0377"},
    {brand: "Adidas", model: "ZX 2K Boost", reference_number: "FX8835"},
    {brand: "Adidas", model: "4D Fusio", reference_number: "FY3602"},
    {brand: "Adidas", model: "Forum Low", reference_number: "FY7756"},
    {brand: "Adidas", model: "Superstar Vegan", reference_number: "FW2295"},
    {brand: "Adidas", model: "Yeezy Foam Runner", reference_number: "GV7903"},
    {brand: "Adidas", model: "Terrex Free Hiker Primeblue", reference_number: "FX9255"},
    {brand: "Adidas", model: "Predator Freak.1", reference_number: "FW7328"},
    {brand: "Adidas", model: "FYW XTA", reference_number: "FX9153"},
    {brand: "Nike", model: "Air Max 1", reference_number: "FD9082"},
    {brand: "Nike", model: "Air Max 90", reference_number: "CW7483"},
    {brand: "Nike", model: "Air Force 1 '07", reference_number: "315122"},
    {brand: "Nike", model: "Air Jordan 1 Retro High OG", reference_number: "555088"},
    {brand: "Nike", model: "React Infinity Run Flyknit", reference_number: "CD4371"},
    {brand: "Nike", model: "Blazer Mid '77 Vintage", reference_number: "BQ6806"},
    {brand: "Nike", model: "ZoomX Vaporfly NEXT%", reference_number: "AO4568"},
    {brand: "Nike", model: "Dunk Low", reference_number: "DD1391"},
    {brand: "Nike", model: "Metcon 6", reference_number: "CT1241"},
    {brand: "Nike", model: "Pegasus Trail 3", reference_number: "DA8697"},
    {brand: "Nike", model: "SB Dunk Low Pro", reference_number: "BQ6817"},
    {brand: "Nike", model: "Air Zoom Alphafly NEXT%", reference_number: "CI9925"},
    {brand: "Nike", model: "Air Max 270 React", reference_number: "CT1264"},
    {brand: "Nike", model: "Air Zoom Tempo NEXT%", reference_number: "CI9923"},
    {brand: "Nike", model: "Air Zoom Pegasus 37", reference_number: "BQ9646"},
    {brand: "Nike", model: "Space Hippie 01", reference_number: "CJ1646"},
    {brand: "Nike", model: "Air Jordan 5 Retro", reference_number: "CT4838"},
    {brand: "Nike", model: "Air Max 2090", reference_number: "BV9977"},
    {brand: "Nike", model: "React Vision", reference_number: "CD4373"},
    {brand: "Nike", model: "Air Jordan 3 Retro", reference_number: "CT8532"},
    {brand: "Nike", model: "SB Dunk High Pro", reference_number: "CZ8149"},
    {brand: "Nike", model: "LeBron 18", reference_number: "CQ9283"},
    {brand: "Nike", model: "Kyrie 7", reference_number: "CQ9327"},
    {brand: "Nike", model: "Mercurial Vapor 14 Elite FG", reference_number: "CV0993"},
    {brand: "Nike", model: "Tiempo Legend 9 Elite FG", reference_number: "CZ8482"},
    {brand: "Nike", model: "Phantom GT Elite FG", reference_number: "CK8439"},
    {brand: "Nike", model: "Waffle One", reference_number: "DA7995"},
    {brand: "Nike", model: "Air Huarache", reference_number: "DD1068"},
    {brand: "Nike", model: "Cortez Basic Leather", reference_number: "819719"},
    {brand: "Nike", model: "Air Max Pre-Day", reference_number: "DD0338"},
    {brand: "Puma", model: "Suede Classic", reference_number: "352634"},
    {brand: "Puma", model: "RS-X", reference_number: "369579"},
    {brand: "Puma", model: "Cali", reference_number: "369155"},
    {brand: "Puma", model: "Future Rider", reference_number: "371149"},
    {brand: "Puma", model: "LQDCell Optic", reference_number: "192560"},
    {brand: "Puma", model: "Cell Alien OG", reference_number: "369801"},
    {brand: "Puma", model: "Thunder Spectra", reference_number: "367516"},
    {brand: "Puma", model: "Ralph Sampson Lo", reference_number: "370847"},
    {brand: "Puma", model: "Basket Classic", reference_number: "354367"},
    {brand: "Puma", model: "Ignite Limitless", reference_number: "189987"},
    {brand: "Puma", model: "Calibrate Runner", reference_number: "193698"},
    {brand: "Puma", model: "Future Z 1.1", reference_number: "106028"},
    {brand: "Puma", model: "Ultra 1.1", reference_number: "106044"},
    {brand: "Puma", model: "RS-Dreamer", reference_number: "193990"},
    {brand: "Puma", model: "Mirage Mox", reference_number: "375167"},
    {brand: "Puma", model: "RS-Fast", reference_number: "380562"},
    {brand: "Puma", model: "Wild Rider", reference_number: "381517"},
    {brand: "Puma", model: "Fuse", reference_number: "194419"},
    {brand: "Puma", model: "Deviate Nitro", reference_number: "194441"},
    {brand: "Puma", model: "Magnify Nitro", reference_number: "195171"},
    {brand: "Puma", model: "Eternity Nitro", reference_number: "195102"},
    {brand: "Puma", model: "Liberate Nitro", reference_number: "195065"},
    {brand: "Puma", model: "Velocity Nitro", reference_number: "194598"},
    {brand: "Puma", model: "Spectra", reference_number: "195233"},
    {brand: "Puma", model: "Oslo-City", reference_number: "380743"},
    {brand: "Reebok", model: "Club C 85", reference_number: "AR0456"},
    {brand: "Reebok", model: "Classic Leather", reference_number: "49799"},
    {brand: "Reebok", model: "Nano 9", reference_number: "DV6343"},
    {brand: "Reebok", model: "Floatride Run", reference_number: "CN2592"},
    {brand: "Reebok", model: "Instapump Fury", reference_number: "V47514"},
    {brand: "Reebok", model: "Zig Kinetica", reference_number: "EH1721"},
    {brand: "Reebok", model: "Question Mid", reference_number: "EF7598"},
    {brand: "Reebok", model: "Sole Fury", reference_number: "DV4486"},
    {brand: "Reebok", model: "Legacy Lifter", reference_number: "CN1001"},
    {brand: "Reebok", model: "Aztrek 96", reference_number: "DV6755"},
    {brand: "Reebok", model: "Nano X1", reference_number: "H02868"},
    {brand: "Reebok", model: "Floatride Energy 3", reference_number: "FY7756"},
    {brand: "Reebok", model: "Zig Dynamica", reference_number: "H01256"},
    {brand: "Reebok", model: "Forever Floatride Energy 2", reference_number: "DV6228"},
    {brand: "Reebok", model: "BB 4000 II", reference_number: "GX0601"},
    {brand: "Reebok", model: "Club C Double", reference_number: "FW7790"},
    {brand: "Reebok", model: "Reebok x Cardi B Club C", reference_number: "FW8720"},
    {brand: "Reebok", model: "Answer V", reference_number: "EF7602"},
    {brand: "Reebok", model: "DMX Trail Shadow", reference_number: "DV9316"},
    {brand: "Reebok", model: "Classic Nylon", reference_number: "CN7023"},
    {brand: "Reebok", model: "Royal Turbo Impulse", reference_number: "DV6630"},
    {brand: "Reebok", model: "Legacy 83", reference_number: "FX2588"},
    {brand: "Reebok", model: "Zig Kinetica II", reference_number: "H67945"},
    {brand: "Reebok", model: "Instapump Fury Zone", reference_number: "GZ5363"},
    {brand: "Reebok", model: "Premier Road Modern", reference_number: "H01350"},
    {brand: "Reebok", model: "Reebok x Maison Margiela Tabi Instapump Fury", reference_number: "FX1407"},
    {brand: "Reebok", model: "Reebok x Pyer Moss Experiment 4", reference_number: "H01891"},
    {brand: "Reebok", model: "Club C Revenge", reference_number: "FX1129"},
    {brand: "Reebok", model: "CL Legacy", reference_number: "FY7557"},
    {brand: "Reebok", model: "Beatnik", reference_number: "FY2949"}
]

